# Generated by Django 4.2.23 on 2025-10-08 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube')], default='youtube', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='youtube', max_length=32)),
                ('on_platform_id', models.CharField(db_index=True, max_length=32)),
                ('language', models.CharField(default='ru', max_length=8)),
                ('duration', models.IntegerField(help_text='seconds')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.CharField(blank=True, max_length=16)),
                ('rating', models.FloatField(default=0.0)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=32)),
                ('premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='videos.channel')),
                ('speakers', models.ManyToManyField(blank=True, related_name='videos', to='videos.speaker')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='videos.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['upload_date'], name='videos_vide_upload__339bc0_idx'), models.Index(fields=['premium'], name='videos_vide_premium_152fd8_idx'), models.Index(fields=['level'], name='videos_vide_level_ff33bd_idx')],
            },
        ),
    ]
