# Generated by Django 4.2.23 on 2025-10-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_expand_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='level',
            field=models.CharField(choices=[('Beginner 0', 'Beginner 0'), ('Beginner 1', 'Beginner 1'), ('Beginner 2', 'Beginner 2'), ('Intermediate 1', 'Intermediate 1'), ('Intermediate 2', 'Intermediate 2'), ('Advanced', 'Advanced'), ('Native', 'Native')], default='Beginner 0', max_length=32),
        ),
    ]
