# Generated by Django 4.2.23 on 2025-10-08 20:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0004_alter_offplatformlog_user_alter_userviewlog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=128)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_freqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-count', 'word'],
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='UserViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_date', models.DateTimeField(db_index=True)),
                ('watch_time', models.IntegerField(default=0)),
                ('video_time_start', models.FloatField(default=0.0)),
                ('video_time_end', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_logs', to='platform.video')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'watch_date'], name='journal_use_user_id_fc1799_idx')],
            },
        ),
        migrations.CreateModel(
            name='OffPlatformLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_duration', models.IntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('comment', models.TextField(blank=True, default='')),
                ('activity', models.CharField(choices=[('listening_watching', 'Listening/Watching'), ('reading', 'Reading'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('other', 'Other')], default='listening_watching', max_length=32)),
                ('attention_rate', models.CharField(blank=True, choices=[('active', 'Active 80–100%'), ('passive', 'Passive 20–80%'), ('radio', 'Radio 0–20%')], max_length=16, null=True)),
                ('reality_rates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None)),
                ('comprehensibility_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_input_minutes_snapshot', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_platform_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_start'],
                'indexes': [models.Index(fields=['user', 'date_start'], name='journal_off_user_id_662c31_idx')],
            },
        ),
    ]
