# Generated by Django 4.2.23 on 2025-09-27 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=128)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_freqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-count', 'word'],
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='UserViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_date', models.DateTimeField(db_index=True)),
                ('watch_time', models.IntegerField(default=0)),
                ('video_time_start', models.FloatField(default=0.0)),
                ('video_time_end', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_logs', to='platform.video')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'watch_date'], name='platform_us_user_id_0fb537_idx')],
            },
        ),
        migrations.CreateModel(
            name='OffPlatformLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_duration', models.IntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('comment', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_platform_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_start'],
                'indexes': [models.Index(fields=['user', 'date_start'], name='platform_of_user_id_4f66fb_idx')],
            },
        ),
    ]
