# Generated by Django 4.2.23 on 2025-09-27 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_userwordfrequency_userviewlog_offplatformlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='offplatformlog',
            name='activity',
            field=models.CharField(choices=[('listening_watching', 'Listening/Watching'), ('reading', 'Reading'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('other', 'Other')], default='listening_watching', max_length=32),
        ),
        migrations.AddField(
            model_name='offplatformlog',
            name='attention_rate',
            field=models.CharField(blank=True, choices=[('active', 'Active 80–100%'), ('passive', 'Passive 20–80%'), ('radio', 'Radio 0–20%')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='offplatformlog',
            name='comprehensibility_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offplatformlog',
            name='reality_rates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='offplatformlog',
            name='total_input_minutes_snapshot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
