# Generated by Django 4.2.23 on 2025-10-08 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platform', '0003_offplatformlog_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offplatformlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_platform_logs_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userviewlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userviewlog',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_logs_old', to='platform.video'),
        ),
        migrations.AlterField(
            model_name='userwordfrequency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_freqs_old', to=settings.AUTH_USER_MODEL),
        ),
    ]
